name: Build and test

on:
  push:
    branches:
      - main
      - master
  pull_request: []

jobs:
  test:
    runs-on: ubuntu-latest
    name: Erlang ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['23.3.4.7', '24.1']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - name: "Build"
        run: "make"
      - name: "Run tests"
        run: "make tests"
      - name: "Run property-based tests"
        run: "PROP_NUMTESTS=5000 rebar3 ct --suite test/gradualizer_prop_SUITE.erl"
        continue-on-error: true
      - name: "Self-gradualize"
        run: "make gradualize"
        continue-on-error: true
